site_name: gdalxarray
site_url: https://hypertidy.github.io/gdalxarray/
repo_url: https://github.com/hypertidy/gdalxarray
docs_dir: docs

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            docstring_style: numpy

nav:
  - Home: index.md
  - Install: install.md
  - Cookbook: cookbook.md
  - API Reference: api.md
  - Changelog: changelog.md
