[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "gdalxarray/__init__.py"

[project]
name = "gdalxarray"
dynamic = ["version"]
description = "xarray extension for GDAL"
authors = [
    {name = "Michael Sumner", email = "mdsumner@gmail.com"},
]
keywords = [
    "GDAL",
    "xarray",
    "osgeo"
]
readme = "README.md"
license = {text = "Apache"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: GIS",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
requires-python = ">=3.8"
dependencies = [
    "packaging",
    "affine",
    "rasterix",
    "xarray>=2025.6",
  #  "GDAL>=3.10.0",
]


#[project.entry-points."xarray.backends"]
#gdal = "gdalxarray.gdalxarray:GDALBackendEntrypoint"
